function breath_yes() {
    document.getElementById('placeholder').style.display = "block";
    document.getElementById('minor').style.display = "none";
    document.getElementById("delayed").style.display = "none";
    document.getElementById("immediate").style.display = "none";
    document.getElementById('expectant').style.display = "none";
    document.getElementById('q1').style.display = "block";
    document.getElementById('q2').style.display = "none";
    document.getElementById('q3').style.display = "none";
    document.getElementById('q4').style.display = "none";
    document.getElementById('injury').style.display = "none";
    document.getElementById('survival').style.display = "none";
    document.getElementById('q1explain').style.display = "none";
    document.getElementById('q2explain').style.display = "none";
    document.getElementById('q3explain').style.display = "block";
    document.getElementById('q3-2explain').style.display = "none";
    document.getElementById('q4explain').style.display = "none";
    document.getElementById('q4-2explain').style.display = "none";
    document.getElementById('q5explain').style.display = "none";
    document.getElementById('q5-2explain').style.display = "none";
    document.getElementById('q6explain').style.display = "none";
    document.getElementById('q6-2explain').style.display = "none";
    document.getElementById('q7explain').style.display = "none";
}

   function breath_no() {
   document.getElementById('placeholder').style.display = "none";
   document.getElementById("minor").style.display = "none";
   document.getElementById("delayed").style.display = "none";
   document.getElementById("immediate").style.display = "none";
   document.getElementById('expectant').style.display = "block";
   document.getElementById('q1').style.display = "none";
   document.getElementById('q2').style.display = "none";
   document.getElementById('q3').style.display = "none";
   document.getElementById('q4').style.display = "none";
   document.getElementById('injury').style.display = "none";
   document.getElementById('survival').style.display = "none";
   document.getElementById('q1explain').style.display = "none";
   document.getElementById('q2explain').style.display = "block";
   document.getElementById('q3explain').style.display = "none";
   document.getElementById('q3-2explain').style.display = "none";
   document.getElementById('q4explain').style.display = "none";
   document.getElementById('q4-2explain').style.display = "none";
   document.getElementById('q5explain').style.display = "none";
   document.getElementById('q5-2explain').style.display = "none";
   document.getElementById('q6explain').style.display = "none";
   document.getElementById('q6-2explain').style.display = "none";
   document.getElementById('q7explain').style.display = "none";
}

function q1_yes() {
   document.getElementById('placeholder').style.display = "block";
   document.getElementById("minor").style.display = "none";
   document.getElementById("delayed").style.display = "none";
   document.getElementById("immediate").style.display = "none";
   document.getElementById('expectant').style.display = "none";
   document.getElementById('q2').style.display = "block";
   document.getElementById('q3').style.display = "none";
   document.getElementById('q4').style.display = "none";
   document.getElementById('injury').style.display = "none";
   document.getElementById('survival').style.display = "none";
   document.getElementById('q1explain').style.display = "none";
   document.getElementById('q2explain').style.display = "none";
   document.getElementById('q3explain').style.display = "none";
   document.getElementById('q3-2explain').style.display = "none";
   document.getElementById('q4explain').style.display = "block";
   document.getElementById('q4-2explain').style.display = "none";
   document.getElementById('q5explain').style.display = "none";
   document.getElementById('q5-2explain').style.display = "none";
   document.getElementById('q6explain').style.display = "none";
   document.getElementById('q6-2explain').style.display = "none";
   document.getElementById('q7explain').style.display = "none";
}

function q1_no() {
   document.getElementById('placeholder').style.display = "block";
   document.getElementById("minor").style.display = "none";
   document.getElementById("delayed").style.display = "none";
   document.getElementById("immediate").style.display = "none";
   document.getElementById('expectant').style.display = "none";
   document.getElementById('q2').style.display = "none";
   document.getElementById('q3').style.display = "none";
   document.getElementById('q4').style.display = "none";
   document.getElementById('injury').style.display = "none";
   document.getElementById('survival').style.display = "block";
   document.getElementById('q1explain').style.display = "none";
   document.getElementById('q2explain').style.display = "none";
   document.getElementById('q3explain').style.display = "none";
   document.getElementById('q3-2explain').style.display = "block";
   document.getElementById('q4explain').style.display = "none";
   document.getElementById('q4-2explain').style.display = "none";
   document.getElementById('q5explain').style.display = "none";
   document.getElementById('q5-2explain').style.display = "none";
   document.getElementById('q6explain').style.display = "none";
   document.getElementById('q6-2explain').style.display = "none";
   document.getElementById('q7explain').style.display = "none";
}

function q2_yes() {
   document.getElementById('placeholder').style.display = "block";
   document.getElementById("minor").style.display = "none";
   document.getElementById("delayed").style.display = "none";
   document.getElementById("immediate").style.display = "none";
   document.getElementById('expectant').style.display = "none";
   document.getElementById('q3').style.display = "block";
   document.getElementById('q4').style.display = "none";
   document.getElementById('injury').style.display = "none";
   document.getElementById('survival').style.display = "none";
   document.getElementById('q1explain').style.display = "none";
   document.getElementById('q2explain').style.display = "none";
   document.getElementById('q3explain').style.display = "none";
   document.getElementById('q3-2explain').style.display = "none";
   document.getElementById('q4explain').style.display = "none";
   document.getElementById('q4-2explain').style.display = "none";
   document.getElementById('q5explain').style.display = "block";
   document.getElementById('q5-2explain').style.display = "none";
   document.getElementById('q6explain').style.display = "none";
   document.getElementById('q6-2explain').style.display = "none";
   document.getElementById('q7explain').style.display = "none";
}

function q2_no() {
   document.getElementById('placeholder').style.display = "block";
   document.getElementById("minor").style.display = "none";
   document.getElementById("delayed").style.display = "none";
   document.getElementById("immediate").style.display = "none";
   document.getElementById('expectant').style.display = "none";
   document.getElementById('q3').style.display = "none";
   document.getElementById('q4').style.display = "none";
   document.getElementById('injury').style.display = "none";
   document.getElementById('survival').style.display = "block";
   document.getElementById('q1explain').style.display = "none";
   document.getElementById('q2explain').style.display = "none";
   document.getElementById('q3explain').style.display = "none";
   document.getElementById('q3-2explain').style.display = "none";
   document.getElementById('q4explain').style.display = "none";
   document.getElementById('q4-2explain').style.display = "block";
   document.getElementById('q5explain').style.display = "none";
   document.getElementById('q5-2explain').style.display = "none";
   document.getElementById('q6explain').style.display = "none";
   document.getElementById('q6-2explain').style.display = "none";
   document.getElementById('q7explain').style.display = "none";
}

function q3_yes() {
   document.getElementById('placeholder').style.display = "block";
   document.getElementById("minor").style.display = "none";
   document.getElementById("delayed").style.display = "none";
   document.getElementById("immediate").style.display = "none";
   document.getElementById('expectant').style.display = "none";
   document.getElementById('q4').style.display = "block";
   document.getElementById('injury').style.display = "none";
   document.getElementById('survival').style.display = "none";
   document.getElementById('q1explain').style.display = "none";
   document.getElementById('q2explain').style.display = "none";
   document.getElementById('q3explain').style.display = "none";
   document.getElementById('q3-2explain').style.display = "none";
   document.getElementById('q4explain').style.display = "none";
   document.getElementById('q4-2explain').style.display = "none";
   document.getElementById('q5explain').style.display = "none";
   document.getElementById('q5-2explain').style.display = "none";
   document.getElementById('q6explain').style.display = "block";
   document.getElementById('q6-2explain').style.display = "none";
   document.getElementById('q7explain').style.display = "none";
}

function q3_no() {
   document.getElementById('placeholder').style.display = "block";
   document.getElementById("minor").style.display = "none";
   document.getElementById("delayed").style.display = "none";
   document.getElementById("immediate").style.display = "none";
   document.getElementById('expectant').style.display = "none";
   document.getElementById('q4').style.display = "none";
   document.getElementById('injury').style.display = "none";
   document.getElementById('survival').style.display = "block";
   document.getElementById('q1explain').style.display = "none";
   document.getElementById('q2explain').style.display = "none";
   document.getElementById('q3explain').style.display = "none";
   document.getElementById('q3-2explain').style.display = "none";
   document.getElementById('q4explain').style.display = "none";
   document.getElementById('q4-2explain').style.display = "none";
   document.getElementById('q5explain').style.display = "none";
   document.getElementById('q5-2explain').style.display = "block";
   document.getElementById('q6explain').style.display = "none";
   document.getElementById('q6-2explain').style.display = "none";
   document.getElementById('q7explain').style.display = "none";
}

function q4_yes() {
   document.getElementById('placeholder').style.display = "block";
   document.getElementById("minor").style.display = "none";
   document.getElementById("delayed").style.display = "none";
   document.getElementById("immediate").style.display = "none";
   document.getElementById('expectant').style.display = "none";
   document.getElementById('injury').style.display = "block";
   document.getElementById('survival').style.display = "none";
   document.getElementById('q1explain').style.display = "none";
   document.getElementById('q2explain').style.display = "none";
   document.getElementById('q3explain').style.display = "none";
   document.getElementById('q3-2explain').style.display = "none";
   document.getElementById('q4explain').style.display = "none";
   document.getElementById('q4-2explain').style.display = "none";
   document.getElementById('q5explain').style.display = "none";
   document.getElementById('q5-2explain').style.display = "none";
   document.getElementById('q6explain').style.display = "none";
   document.getElementById('q6-2explain').style.display = "none";
   document.getElementById('q7explain').style.display = "block";
}

function q4_no() {
   document.getElementById('placeholder').style.display = "block";
   document.getElementById("minor").style.display = "none";
   document.getElementById("delayed").style.display = "none";
   document.getElementById("immediate").style.display = "none";
   document.getElementById('expectant').style.display = "none";
   document.getElementById('injury').style.display = "none";
   document.getElementById('survival').style.display = "block";
   document.getElementById('q1explain').style.display = "none";
   document.getElementById('q2explain').style.display = "none";
   document.getElementById('q3explain').style.display = "none";
   document.getElementById('q3-2explain').style.display = "none";
   document.getElementById('q4explain').style.display = "none";
   document.getElementById('q4-2explain').style.display = "none";
   document.getElementById('q5explain').style.display = "none";
   document.getElementById('q5-2explain').style.display = "none";
   document.getElementById('q6explain').style.display = "none";
   document.getElementById('q6-2explain').style.display = "block";
   document.getElementById('q7explain').style.display = "none";
}

function injury_yes() {
   document.getElementById('placeholder').style.display = "none";
   document.getElementById("minor").style.display = "block";
   document.getElementById("delayed").style.display = "none";
   document.getElementById("immediate").style.display = "none";
   document.getElementById('expectant').style.display = "none";
   document.getElementById('survival').style.display = "none";
   document.getElementById('q1explain').style.display = "none";
   document.getElementById('q2explain').style.display = "none";
   document.getElementById('q3explain').style.display = "none";
   document.getElementById('q3-2explain').style.display = "none";
   document.getElementById('q4explain').style.display = "none";
   document.getElementById('q4-2explain').style.display = "none";
   document.getElementById('q5explain').style.display = "none";
   document.getElementById('q5-2explain').style.display = "none";
   document.getElementById('q6explain').style.display = "none";
   document.getElementById('q6-2explain').style.display = "none";
   document.getElementById('q7explain').style.display = "block";
}

function injury_no() {
   document.getElementById('placeholder').style.display = "none";
   document.getElementById("minor").style.display = "none";
   document.getElementById("delayed").style.display = "block";
   document.getElementById("immediate").style.display = "none";
   document.getElementById('expectant').style.display = "none";
   document.getElementById('survival').style.display = "none";
   document.getElementById('q1explain').style.display = "none";
   document.getElementById('q2explain').style.display = "none";
   document.getElementById('q3explain').style.display = "none";
   document.getElementById('q3-2explain').style.display = "none";
   document.getElementById('q4explain').style.display = "none";
   document.getElementById('q4-2explain').style.display = "none";
   document.getElementById('q5explain').style.display = "none";
   document.getElementById('q5-2explain').style.display = "none";
   document.getElementById('q6explain').style.display = "none";
   document.getElementById('q6-2explain').style.display = "none";
   document.getElementById('q7explain').style.display = "block";
}

function survival_yes() {
   document.getElementById('placeholder').style.display = "none";
   document.getElementById("minor").style.display = "none";
   document.getElementById("delayed").style.display = "none";
   document.getElementById("immediate").style.display = "block";
   document.getElementById('expectant').style.display = "none";
   document.getElementById('injury').style.display = "none";
   document.getElementById('q1explain').style.display = "none";
   document.getElementById('q2explain').style.display = "none";
   document.getElementById('q3explain').style.display = "none";
   document.getElementById('q3-2explain').style.display = "none";
   document.getElementById('q4explain').style.display = "none";
   document.getElementById('q4-2explain').style.display = "none";
   document.getElementById('q5explain').style.display = "none";
   document.getElementById('q5-2explain').style.display = "none";
   document.getElementById('q6explain').style.display = "none";
   document.getElementById('q6-2explain').style.display = "block";
   document.getElementById('q7explain').style.display = "none";
}

function survival_no() {
   document.getElementById('placeholder').style.display = "none";
   document.getElementById("minor").style.display = "none";
   document.getElementById("delayed").style.display = "none";
   document.getElementById("immediate").style.display = "none";
   document.getElementById('expectant').style.display = "block";
   document.getElementById('injury').style.display = "none";
   document.getElementById('q1explain').style.display = "none";
   document.getElementById('q2explain').style.display = "none";
   document.getElementById('q3explain').style.display = "none";
   document.getElementById('q3-2explain').style.display = "none";
   document.getElementById('q4explain').style.display = "none";
   document.getElementById('q4-2explain').style.display = "none";
   document.getElementById('q5explain').style.display = "none";
   document.getElementById('q5-2explain').style.display = "none";
   document.getElementById('q6explain').style.display = "none";
   document.getElementById('q6-2explain').style.display = "block";
   document.getElementById('q7explain').style.display = "none";
} 

function refresh() {
    window.location.reload();
  }
